[true_values]
alpha = 1.3
beta = 0.97
n_samples = 10_000

[data]
filename = "data/samples.arrow"

[updating]
warmup = 2000
n_draws = 4000
n_chains = 7
seed = 1987
filename = "data/chains.arrow"
ncfile = "data/chains.nc"
